### ISSUE TITLE
Instruction installations do not work.

### ISSUE THREAD

**Issue by Captain-Quack** [arjvik/RPN-Ti84#3]
I followed your instructions on how to build/install your program, and the logs indicate there is something wrong with the bash script (anything irrelevant here is omitted with brackets) :
```bash
[...]$ git clone https://github.com/arjvik/RPN-Ti84.git
[...]
[...]$ cd RPN-Ti84/
[...]$ source env.sh
make # Compiles .8xp file
make install # Transfers to calculator (using TiLP)
: command not found
-bash: env.sh: line 12: syntax error: unexpected end of file
makefile:16: *** CEDEV environment path variable is not set.  Stop.
makefile:16: *** CEDEV environment path variable is not set.  Stop.
```
I have tilp installed already. 
Thanks for the help!

**Comment by arjvik** [comment]
Hi!

We can run the installation process manually since the install scripts seem to fail.

Run these commands in the `RPN-Ti84/` folder:

```bash
export CEDEV="$PWD/.toolchain"
export PATH="$PWD/.fasmg:$PWD/.toolchain/bin:$PATH"
make
make install
```

**Comment by arjvik** [comment]
Should also add that if you don't intend to edit the code, you're welcome to download the pre-compiled binary from Releases:

https://github.com/arjvik/RPN-Ti84/releases/download/2.2/RPN2ASM.8xp
